TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += lkshtemp.db
DATA += lkshtemp.proto

#=======================================
include $(TOP)/configure/RULES
